#!/usr/bin/env perl

use strict;
use warnings;

my $FPS = 30;

my $playout_command = $ENV{'REPLAY_PLAYOUT_CMD'};

my $time_shift = shift @ARGV;
my $speed = shift @ARGV; 
my $all_mark_args = join ' ', @ARGV;
chomp(my $timecode_out = `all_mark $all_mark_args`);
my @timecodes = split / /, $timecode_out;

while (1) {
	print "Please select your source. Then press ENTER for replay. Or Ctrl-C to exit.\n";
	chomp(my $source = <STDIN>);

	my $ctrl_file = $ARGV[$source * 2];
	my $data_file = $ARGV[$source * 2 + 1];

	my $timecode = $timecodes[$source] - $time_shift;

	my $frames = $timecode % $FPS;
	my $seconds = $timecode / $FPS;
	my $minutes = $seconds / 60;
	$seconds %= 60;
	my $hours = $minutes / 60;
	$minutes %= 60;

	my $tc_str = sprintf "%02d:%02d:%02d:%02d", $hours, $minutes, $seconds, $frames;

	system("$playout_command $ctrl_file $data_file $tc_str $speed");
}
